"""cascade try: end-to-end verification run with a built-in toy story.

Lets a user verify the full plan -> code -> test pipeline without
touching their real repo. Operates entirely in a temp directory with a
disposable language-appropriate project, then cleans up.

Why this matters: the gap between "cascade doctor says green" and "I'm
willing to bet my real repo on this" is huge. `cascade try` closes that
gap by showing the user a real run, real LLM call, real generated code,
real test execution, with zero risk.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .progress import ProgressReporter

from .coder import generate_code
from .exceptions import CascadeError
from .languages import PYTHON, LanguageProfile
from .llm import LLMClient
from .memory import TeamMemory
from .plan_schemas import CodeChange, FileAction, Plan, TestResult
from .planner import plan_story
from .repo_scan import scan_repo
from .schemas import (
    AcceptanceCriterion,
    Story,
    StorySize,
    StoryStatus,
)
from .tester import run_tests


logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class DemoResult:
    """Outcome of a single cascade try run."""

    plan: Plan
    code_change: CodeChange
    test_result: TestResult
    workspace: Path  # where the demo ran (cleaned up after unless --keep)
    success: bool  # True if every stage completed without error
    total_llm_cost_usd: float = 0.0
    total_input_tokens: int = 0
    total_output_tokens: int = 0


# The toy story: a /hello endpoint. Simple enough that any LLM should
# handle it. Real enough that the test execution is meaningful.
TOY_STORY = Story(
    id="story-cascade-try-001",
    title="Add a hello() function that returns the string 'world'",
    description=(
        "As a developer evaluating Cascade, I want a known-good toy story "
        "to run end-to-end so that I can verify my installation is healthy."
    ),
    acceptance_criteria=[
        AcceptanceCriterion(
            given="the project has no hello() function yet",
            when="hello() is called with no arguments",
            then="it returns the string 'world'",
        ),
    ],
    size=StorySize.XS,
    confidence=100,
    source_meeting_id="cascade-try-builtin",
    notes=(
        "This story is generated by `cascade try` to verify the pipeline. "
        "It is NOT a real user story and should never be built into a real repo."
    ),
    status=StoryStatus.APPROVED,
)


def create_demo_workspace(language: LanguageProfile, root: Path) -> Path:
    """Initialize a minimal language-appropriate project in `root`.

    Just enough scaffolding for the language's test runner to discover
    and run tests. Specifically for Python: a pyproject.toml, a src/
    package, and an empty tests/ directory.

    Returns the workspace path.
    """
    if language.name != "python":
        raise CascadeError(
            f"`cascade try` currently only supports Python projects. "
            f"More languages coming. (Detected: {language.name})"
        )

    root.mkdir(parents=True, exist_ok=True)
    (root / "pyproject.toml").write_text(
        '[project]\nname = "cascade-demo"\nversion = "0.0.1"\n'
        'requires-python = ">=3.11"\ndependencies = []\n'
        "\n[build-system]\n"
        'requires = ["setuptools>=61"]\n'
        'build-backend = "setuptools.build_meta"\n'
        "\n[tool.setuptools.packages.find]\n"
        'where = ["src"]\n'
    )
    (root / "src").mkdir(exist_ok=True)
    (root / "src" / "cascade_demo").mkdir(exist_ok=True)
    (root / "src" / "cascade_demo" / "__init__.py").write_text("")
    (root / "tests").mkdir(exist_ok=True)
    (root / "tests" / "__init__.py").write_text("")

    # Initialize git so the rest of the pipeline doesn't complain
    try:
        subprocess.run(["git", "init", "-q"], cwd=root, check=True)
        subprocess.run(
            ["git", "config", "user.email", "demo@cascade.local"], cwd=root, check=True
        )
        subprocess.run(
            ["git", "config", "user.name", "Cascade Demo"], cwd=root, check=True
        )
        subprocess.run(["git", "add", "-A"], cwd=root, check=True)
        subprocess.run(
            ["git", "commit", "-q", "-m", "initial demo workspace"],
            cwd=root,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise CascadeError(
            f"Could not initialize git in demo workspace: {exc}"
        ) from exc

    return root


def run_demo(
    *,
    llm: LLMClient,
    language: Optional[LanguageProfile] = None,
    keep_workspace: bool = False,
    progress: Optional["ProgressReporter"] = None,
) -> DemoResult:
    """Run a built-in toy story through the pipeline end-to-end.

    Args:
        llm: A configured LLM client (caller provides; doctor verifies it works).
        language: Language profile to use; defaults to Python.
        keep_workspace: If True, don't clean up the temp directory at the end.
            Useful for debugging when something fails.
        progress: Optional ProgressReporter; defaults to silent NoopProgress.
            The CLI passes a RichProgress to get animated spinners.

    Returns:
        A DemoResult with the plan, code change, test result, and the
        workspace path (which is gone unless keep_workspace=True).

    Raises:
        CascadeError: If any stage fails. The exception preserves the
            workspace if keep_workspace=True so the user can inspect it.
    """
    from .progress import NoopProgress, ProgressReporter

    profile = language or PYTHON
    progress = progress or NoopProgress()

    # Create the disposable workspace
    workspace = Path(tempfile.mkdtemp(prefix="cascade-try-"))

    try:
        with progress.stage("setup", "creating disposable workspace") as p:
            create_demo_workspace(profile, workspace)
            p.succeed(f"workspace at {workspace.name}")

        # PLAN
        with progress.stage("plan", "asking LLM to plan the change") as p:
            repo_summary = scan_repo(workspace, profile)
            plan_result = plan_story(
                story=TOY_STORY,
                llm=llm,
                language=profile,
                memory=None,
                repo_summary=repo_summary,
                max_output_tokens=4096,
            )
            plan = plan_result.plan
            p.succeed(f"{len(plan.files)} file(s) to change")

        # CODE
        with progress.stage("code", "asking LLM to write the code + tests") as p:
            code_result = generate_code(
                story=TOY_STORY,
                plan=plan,
                llm=llm,
                language=profile,
                repo_root=workspace,
                memory=None,
                max_output_tokens=8192,
            )
            change = code_result.change
            p.succeed(f"{len(change.files)} file(s) generated")

        # APPLY
        with progress.stage("apply", "writing files to disk"):
            from .repo import apply_code_change

            apply_code_change(workspace, change)

        # TEST -- skip if pytest isn't installed; the user can install it
        with progress.stage("test", "running the test suite") as p:
            test_result = run_tests(workspace, profile, timeout_seconds=60.0)
            if test_result.passed:
                p.succeed(test_result.summary or "passed")
            else:
                p.fail(test_result.summary or "failed")

        success = test_result.passed
        total_in = plan_result.usage.input_tokens + code_result.usage.input_tokens
        total_out = plan_result.usage.output_tokens + code_result.usage.output_tokens
        total_cost = (
            plan_result.usage.estimated_cost_usd
            + code_result.usage.estimated_cost_usd
        )
        return DemoResult(
            plan=plan,
            code_change=change,
            test_result=test_result,
            workspace=workspace,
            success=success,
            total_llm_cost_usd=total_cost,
            total_input_tokens=total_in,
            total_output_tokens=total_out,
        )

    finally:
        if not keep_workspace:
            shutil.rmtree(workspace, ignore_errors=True)
